import java.awt.Window;
import javax.swing.JFrame;
import java.awt.event.WindowAdapter;
import java.io.PrintWriter;
import java.time.LocalDateTime;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.util.HashMap;

public class ProfessorGUI extends JFrame implements InstructorInterface
{
    private HashMap <String, Boolean> settings;

    public ProfessorGUI() throws ChemberryException
    {
        super("Chemberry Instructor");

        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(ProfessorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(ProfessorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(ProfessorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(ProfessorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        settings = new HashMap<String, Boolean>();
        settings.put("autosave", false);

        initComponents();

        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() 
        {
            @Override
            public void windowClosing(WindowEvent event) 
            {
                closeWindow();
            }
        });

        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents()
    {

        studentTabs = new javax.swing.JTabbedPane();
        labelTextChemberry = new javax.swing.JLabel();
        separatorTitle = new javax.swing.JSeparator();
        labelTextStudentData = new javax.swing.JLabel();
        buttonExperimentSetup = new javax.swing.JButton();
        buttonExperimentBroadcast = new javax.swing.JButton();
        buttonSettings = new javax.swing.JButton();
        labelTextCurrentBehavior = new javax.swing.JLabel();
        scrollpaneDebug = new javax.swing.JScrollPane();
        textAreaDebug = new javax.swing.JTextArea();
        labelCurrentExperiment = new javax.swing.JLabel();
        labelTextCurrentExperiment = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));

        labelTextChemberry.setFont(new java.awt.Font("Tahoma", 3, 26)); // NOI18N
        labelTextChemberry.setText("Chemberry Instructor v0.1");

        labelTextStudentData.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelTextStudentData.setText("Student Data");

        buttonExperimentSetup.setText("Experiment Setup");

        buttonExperimentBroadcast.setText("Broadcast Experiment");

        buttonSettings.setText("Settings");

        labelTextCurrentBehavior.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelTextCurrentBehavior.setText("Notifications");

        textAreaDebug.setEditable(false);
        textAreaDebug.setColumns(20);
        textAreaDebug.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        textAreaDebug.setRows(5);
        textAreaDebug.setText("Welcome to Chemberry Instructor client.\n\nThis is the notifications box, where messages will appear as you interact\nwith the program. Additionally, when students connect or disconnect from\nyour program, you will be notified here.\n\nError messages and other useful\ninformation will periodically appear\nhere.\n\nTo get started, configure or load a pre-made experiment by clicking\n\"Experiment Setup.\" Follow the instructions there, and click \"Broadcast\nExperiment\" once you are finished to send it to all connected students.");
        scrollpaneDebug.setViewportView(textAreaDebug);

        labelCurrentExperiment.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelCurrentExperiment.setText("No experiment selected");

        labelTextCurrentExperiment.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelTextCurrentExperiment.setText("Current Experiment");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(separatorTitle)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(labelTextChemberry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(studentTabs))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(labelTextStudentData)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(164, 164, 164)
                                        .addComponent(labelTextCurrentBehavior))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelCurrentExperiment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(scrollpaneDebug, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(6, 6, 6))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(buttonExperimentSetup)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonExperimentBroadcast)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonSettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(labelTextCurrentExperiment)
                                        .addGap(132, 132, 132)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTextChemberry)
                    .addComponent(buttonExperimentSetup)
                    .addComponent(buttonExperimentBroadcast)
                    .addComponent(buttonSettings))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separatorTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTextStudentData)
                    .addComponent(labelTextCurrentExperiment))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelCurrentExperiment, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelTextCurrentBehavior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrollpaneDebug, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE))
                    .addComponent(studentTabs))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    // Variables declaration - do not modify                     
    private javax.swing.JButton buttonExperimentBroadcast;
    private javax.swing.JButton buttonExperimentSetup;
    private javax.swing.JButton buttonSettings;
    private javax.swing.JLabel labelCurrentExperiment;
    private javax.swing.JLabel labelTextChemberry;
    private javax.swing.JLabel labelTextCurrentBehavior;
    private javax.swing.JLabel labelTextCurrentExperiment;
    private javax.swing.JLabel labelTextStudentData;
    private javax.swing.JScrollPane scrollpaneDebug;
    private javax.swing.JSeparator separatorTitle;
    private javax.swing.JTabbedPane studentTabs;
    private javax.swing.JTextArea textAreaDebug;
    // End of variables declaration                   

    @Override
    public void receiveUpdate(String update)
    {
        String[] tokens = update.split(":");
        System.out.println("Update msg received by GUI: " + update);
        //System.out.println("Tokenized string: " + tokens.toString());
        System.out.println("Tokenized update: " + tokens[0] + " " + tokens[1]);

        if (tokens[0].equals("h"))
        {
            studentTabs.addTab(tokens[2], new StudentPanel(tokens[1], tokens[2]));
        }
        else if (tokens[0].equals("u"))
        {
            StudentPanelInterface textHolder = getStudentPanelWithIdentifier(tokens[1]);

            if (textHolder == null)
            {
                System.out.println("Couldn't find the tab with matching IP!!!");
            }
            else
            {
                textHolder.append(tokens[2] + "\n");
                textHolder.updateCalculations();
            }
        }
        else if (tokens[0].equals("d"))
        {
            if (settings.get("autosave").equals(true))
            {
                System.out.println("Autosaving a disconnected client");
                // TODO
                // Since this is used elsewhere, maybe condense to a function.
                try
                {
                    LocalDateTime date = LocalDateTime.now();
                    String append = "";

                    append = append.concat(String.valueOf(date.getMonthValue()));
                    append = append.concat("-" + String.valueOf(date.getDayOfMonth()));
                    append = append.concat("-" + String.valueOf(date.getHour()));
                    append = append.concat("-" + String.valueOf(date.getMinute()));

                    StudentPanelInterface panel = getStudentPanelWithIdentifier(tokens[1]);

                    PrintWriter writer = new PrintWriter("./out/" + panel.getName() + "-" + append + ".dat");

                    char[] arr = panel.getStringOfText().toCharArray();

                    for (char ch : arr)
                    {
                        if (ch != '\n')
                        {
                            writer.print(ch);
                        }
                        else
                        {
                            writer.println();
                        }
                    }

                    writer.close();
                }
                catch(IOException ex)
                {
                    ex.printStackTrace();
                }
            }
            
            System.out.println(tokens[1] + " has disconnected");
            studentTabs.remove(getIndexOfPanelWithIdentifier(tokens[1]));
        }
    }

    // This method finds the StudentPanel with the specified ID.
    // TODO: ventually, it should locate panels by name rather than IP to add a layer of abstraction.
    private StudentPanelInterface getStudentPanelWithIdentifier(String identifier) 
    {
        StudentPanelInterface retval = null;
        
        for (int i = 0; i < studentTabs.getTabCount(); i++) 
        {
            StudentPanelInterface spi = (StudentPanelInterface)studentTabs.getComponentAt(i);
            //System.out.println("IP of current spi: " + spi.getIP());
            if (spi.getIP().equals(identifier))
            {
                retval = (StudentPanelInterface)studentTabs.getComponentAt(i);
            }
        }
        
        return retval;
    }

    private int getIndexOfPanelWithIdentifier(String ident)
    {
        System.out.println("Ident searching for is " + ident);
        int retval = 0;
        
        for (int i = 0; i < studentTabs.getTabCount(); i++)
        {
            System.out.println("IP of tab at " + i + " : " + ((StudentPanel)studentTabs.getComponentAt(i)).getIP());
            // TODO
            // Eventually, tabs should have names of students.
            // Then the if statement below should become
            if (((StudentPanel)studentTabs.getComponentAt(i)).getIP().equals(ident))
            //if (studentTabs.getTitleAt(i).equals(ident));
            {
                System.out.println("Found a match");
                retval = i;
            }
        }

        System.out.println("Index is " + retval);
        
        return retval;
    }

    private void closeWindow()
    {
        for (int i = 0; i < studentTabs.getTabCount(); i++)
        {
            StudentPanelInterface spi = (StudentPanelInterface)studentTabs.getComponentAt(i);
            // Make this more abstract.
            ClientConnection conn = new ClientConnection(spi.getIP(), 9648);
            conn.sendString("d:esync");
        }
        
        this.dispose();
        System.exit(0);
    }
}