/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fixedgui;

/**
 *
 * @author Kevin
 */
public class StudentGUI extends javax.swing.JFrame {

    
    /**
     * Creates new form NewJFrame1
     */
    public StudentGUI() 
    {
        initComponents();
        changeComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        dialogConfiguration = new javax.swing.JDialog();
        rbuttonpH = new javax.swing.JRadioButton();
        rbuttonCond = new javax.swing.JRadioButton();
        rbuttonTemp = new javax.swing.JRadioButton();
        labelTextInstrument = new javax.swing.JLabel();
        buttonInstrumentFinish = new javax.swing.JButton();
        buttonInstrumentCancel = new javax.swing.JButton();
        sliderDuration = new javax.swing.JSlider();
        sliderInterval = new javax.swing.JSlider();
        toggleButtonIntervals = new javax.swing.JToggleButton();
        labelTextToggle = new javax.swing.JLabel();
        labelTextInterval = new javax.swing.JLabel();
        labelTextDurationSlider = new javax.swing.JLabel();
        valueOfInterval = new javax.swing.JLabel();
        valueOfDuration = new javax.swing.JLabel();
        instrumentButtons = new javax.swing.ButtonGroup();
        measurementTypeButtons = new javax.swing.ButtonGroup();
        buttonConfigure = new javax.swing.JButton();
        buttonSettings = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        buttonMeasure = new javax.swing.JButton();
        buttonStopMeasure = new javax.swing.JButton();
        buttonVisualize = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        textAreaDataPoints = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        textAreaCurrentReading = new javax.swing.JTextPane();
        buttonSaveData = new javax.swing.JButton();
        buttonOpenData = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaDebug = new javax.swing.JTextArea();
        buttonClearData = new javax.swing.JButton();
        buttonExperimentDetails = new javax.swing.JButton();

        dialogConfiguration.setSize(new java.awt.Dimension(600, 350));
        dialogConfiguration.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        instrumentButtons.add(rbuttonpH);
        rbuttonpH.setText("pH");
        dialogConfiguration.getContentPane().add(rbuttonpH, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 65, -1, -1));

        instrumentButtons.add(rbuttonCond);
        rbuttonCond.setText("Voltage / conductivity");
        dialogConfiguration.getContentPane().add(rbuttonCond, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 131, -1, -1));

        instrumentButtons.add(rbuttonTemp);
        rbuttonTemp.setText("Temperature");
        dialogConfiguration.getContentPane().add(rbuttonTemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 196, -1, -1));

        labelTextInstrument.setText("Instrument Selection:");
        dialogConfiguration.getContentPane().add(labelTextInstrument, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 22, -1, 25));

        buttonInstrumentFinish.setText("Finish");
        dialogConfiguration.getContentPane().add(buttonInstrumentFinish, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 239, -1, -1));

        buttonInstrumentCancel.setText("Cancel");
        buttonInstrumentCancel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonInstrumentCancelActionPerformed(evt);
            }
        });
        dialogConfiguration.getContentPane().add(buttonInstrumentCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 239, -1, -1));

        sliderDuration.setMajorTickSpacing(10);
        sliderDuration.setMaximum(60);
        sliderDuration.setMinimum(5);
        sliderDuration.setMinorTickSpacing(5);
        sliderDuration.setPaintLabels(true);
        sliderDuration.setPaintTicks(true);
        sliderDuration.setSnapToTicks(true);
        dialogConfiguration.getContentPane().add(sliderDuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, -1, -1));

        sliderInterval.setMajorTickSpacing(2);
        sliderInterval.setMaximum(10);
        sliderInterval.setMinorTickSpacing(1);
        sliderInterval.setPaintLabels(true);
        sliderInterval.setPaintTicks(true);
        sliderInterval.setSnapToTicks(true);
        dialogConfiguration.getContentPane().add(sliderInterval, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 65, -1, -1));

        toggleButtonIntervals.setText("Enable Intervals");
        toggleButtonIntervals.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                toggleButtonIntervalsActionPerformed(evt);
            }
        });
        dialogConfiguration.getContentPane().add(toggleButtonIntervals, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 65, -1, -1));

        labelTextToggle.setText("Toggle for interval measurements:");
        dialogConfiguration.getContentPane().add(labelTextToggle, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 26, -1, -1));

        labelTextInterval.setText("Interval (seconds):");
        dialogConfiguration.getContentPane().add(labelTextInterval, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 42, -1, -1));

        labelTextDurationSlider.setText("Duration (seconds):");
        dialogConfiguration.getContentPane().add(labelTextDurationSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 159, -1, -1));
        dialogConfiguration.getContentPane().add(valueOfInterval, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 119, -1, -1));
        dialogConfiguration.getContentPane().add(valueOfDuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 265, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonConfigure.setText("Configuration");
        buttonConfigure.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonConfigureActionPerformed(evt);
            }
        });
        getContentPane().add(buttonConfigure, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 110, 50));

        buttonSettings.setText("Settings");
        getContentPane().add(buttonSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 40, 90, 50));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonMeasure.setText("Measure");
        jPanel1.add(buttonMeasure, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, 30));

        buttonStopMeasure.setText("Stop");
        jPanel1.add(buttonStopMeasure, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 70, 30));

        buttonVisualize.setText("Visualize");
        jPanel1.add(buttonVisualize, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, -1, 30));

        textAreaDataPoints.setColumns(20);
        textAreaDataPoints.setRows(5);
        jScrollPane3.setViewportView(textAreaDataPoints);

        jSplitPane1.setLeftComponent(jScrollPane3);

        jScrollPane4.setViewportView(textAreaCurrentReading);

        jSplitPane1.setRightComponent(jScrollPane4);

        jPanel1.add(jSplitPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 400, 170));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 430, 230));

        buttonSaveData.setText("Save");
        getContentPane().add(buttonSaveData, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 70, 50));

        buttonOpenData.setText("Open");
        buttonOpenData.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonOpenDataActionPerformed(evt);
            }
        });
        getContentPane().add(buttonOpenData, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, -1, 50));

        textAreaDebug.setColumns(20);
        textAreaDebug.setRows(5);
        jScrollPane1.setViewportView(textAreaDebug);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 210, 240));

        buttonClearData.setText("Clear");
        getContentPane().add(buttonClearData, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 80, 50));

        buttonExperimentDetails.setText("Experiment Details");
        getContentPane().add(buttonExperimentDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 170, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonConfigureActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonConfigureActionPerformed
    {//GEN-HEADEREND:event_buttonConfigureActionPerformed
        dialogConfiguration.setVisible(true);
    }//GEN-LAST:event_buttonConfigureActionPerformed

    private void toggleButtonIntervalsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_toggleButtonIntervalsActionPerformed
    {//GEN-HEADEREND:event_toggleButtonIntervalsActionPerformed
        labelTextDurationSlider.setVisible(!(labelTextDurationSlider.isVisible()));
        labelTextInterval.setVisible(!(labelTextInterval.isVisible()));
        sliderInterval.setVisible(!(sliderInterval.isVisible()));
        sliderDuration.setVisible(!(sliderDuration.isVisible()));
    }//GEN-LAST:event_toggleButtonIntervalsActionPerformed

    private void buttonInstrumentCancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonInstrumentCancelActionPerformed
    {//GEN-HEADEREND:event_buttonInstrumentCancelActionPerformed
        dialogConfiguration.setVisible(false);
    }//GEN-LAST:event_buttonInstrumentCancelActionPerformed

    private void buttonOpenDataActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonOpenDataActionPerformed
    {//GEN-HEADEREND:event_buttonOpenDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonOpenDataActionPerformed

    private void changeComponents()
    {
        // Hide all the multimeasure info at first
        labelTextDurationSlider.setVisible(false);
        labelTextInterval.setVisible(false);
        sliderInterval.setVisible(false);
        sliderDuration.setVisible(false);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClearData;
    private javax.swing.JButton buttonConfigure;
    private javax.swing.JButton buttonExperimentDetails;
    private javax.swing.JButton buttonInstrumentCancel;
    private javax.swing.JButton buttonInstrumentFinish;
    private javax.swing.JButton buttonMeasure;
    private javax.swing.JButton buttonOpenData;
    private javax.swing.JButton buttonSaveData;
    private javax.swing.JButton buttonSettings;
    private javax.swing.JButton buttonStopMeasure;
    private javax.swing.JButton buttonVisualize;
    private javax.swing.JDialog dialogConfiguration;
    private javax.swing.ButtonGroup instrumentButtons;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel labelTextDurationSlider;
    private javax.swing.JLabel labelTextInstrument;
    private javax.swing.JLabel labelTextInterval;
    private javax.swing.JLabel labelTextToggle;
    private javax.swing.ButtonGroup measurementTypeButtons;
    private javax.swing.JRadioButton rbuttonCond;
    private javax.swing.JRadioButton rbuttonTemp;
    private javax.swing.JRadioButton rbuttonpH;
    private javax.swing.JSlider sliderDuration;
    private javax.swing.JSlider sliderInterval;
    private javax.swing.JTextPane textAreaCurrentReading;
    private javax.swing.JTextArea textAreaDataPoints;
    private javax.swing.JTextArea textAreaDebug;
    private javax.swing.JToggleButton toggleButtonIntervals;
    private javax.swing.JLabel valueOfDuration;
    private javax.swing.JLabel valueOfInterval;
    // End of variables declaration//GEN-END:variables
}
